name: job_tracker_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.3.6

  # Local Database
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.0.15

  # Routing
  go_router: ^7.1.1

  # Notifications
  flutter_local_notifications: ^14.1.1

  # Calendar
  table_calendar: ^3.0.9

  # Charts
  fl_chart: ^0.62.0

  # File Picker
  file_picker: ^5.3.1

  # Firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5

  # Google Sign In
  google_sign_in: ^6.1.4

  # Other
  intl: ^0.18.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Isar Generator
  isar_generator: ^3.1.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
